In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import re
import string
df=pd.read_csv('email.csv')
df

            Category                                            Message
0                ham  Go until jurong point, crazy.. Available only ...
1                ham                      Ok lar... Joking wif u oni...
2               spam  Free entry in 2 a wkly comp to win FA Cup fina...
3                ham  U dun say so early hor... U c already then say...
4                ham  Nah I don't think he goes to usf, he lives aro...
...              ...                                                ...
5568             ham               Will ü b going to esplanade fr home?
5569             ham  Pity, * was in mood for that. So...any other s...
5570             ham  The guy did some bitching but I acted like i'd...
5571             ham                         Rofl. Its true to its name
5572  {"mode":"full"                                    isActive:false}

[5573 rows x 2 columns]

In [8]:
df.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5573 entries, 0 to 5572
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5573 non-null   object
 1   Message   5573 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [10]:
df['Category'].value_counts()

Category
ham               4825
spam               747
{"mode":"full"       1
Name: count, dtype: int64

In [11]:
df['Category']=df['Category'].replace({
    'ham': 0,
    'spam':1,
    '{"mode":"full"':np.nan
})
df

C:\Users\HP\AppData\Local\Temp\ipykernel_18204\1519069462.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Category']=df['Category'].replace({

      Category                                            Message
0          0.0  Go until jurong point, crazy.. Available only ...
1          0.0                      Ok lar... Joking wif u oni...
2          1.0  Free entry in 2 a wkly comp to win FA Cup fina...
3          0.0  U dun say so early hor... U c already then say...
4          0.0  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5568       0.0               Will ü b going to esplanade fr home?
5569       0.0  Pity, * was in mood for that. So...any other s...
5570       0.0  The guy did some bitching but I acted like i'd...
5571       0.0                         Rofl. Its true to its name
5572       NaN                                    isActive:false}

[5573 rows x 2 columns]

In [12]:
x=df.iloc[::-2]
x

      Category                                            Message
5572       NaN                                    isActive:false}
5570       0.0  The guy did some bitching but I acted like i'd...
5568       0.0               Will ü b going to esplanade fr home?
5566       1.0  REMINDER FROM O2: To get 2.50 pounds free call...
5564       0.0  Why don't you wait 'til at least wednesday to ...
...        ...                                                ...
8          1.0  WINNER!! As a valued network customer you have...
6          0.0  Even my brother is not like to speak with me. ...
4          0.0  Nah I don't think he goes to usf, he lives aro...
2          1.0  Free entry in 2 a wkly comp to win FA Cup fina...
0          0.0  Go until jurong point, crazy.. Available only ...

[2787 rows x 2 columns]

In [13]:
df['Category'].unique()

array([ 0.,  1., nan])

In [14]:
df.dropna(inplace = True)

In [15]:
df

      Category                                            Message
0          0.0  Go until jurong point, crazy.. Available only ...
1          0.0                      Ok lar... Joking wif u oni...
2          1.0  Free entry in 2 a wkly comp to win FA Cup fina...
3          0.0  U dun say so early hor... U c already then say...
4          0.0  Nah I don't think he goes to usf, he lives aro...
...        ...                                                ...
5567       1.0  This is the 2nd time we have tried 2 contact u...
5568       0.0               Will ü b going to esplanade fr home?
5569       0.0  Pity, * was in mood for that. So...any other s...
5570       0.0  The guy did some bitching but I acted like i'd...
5571       0.0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [16]:
def wordopt(text):
    text = text.lower()
    text = re.sub(r'https?://\S+|www\.\S+', '', text)
    text = re.sub(r'<.*?>', '', text)
    text = re.sub(r'\[.*?\]', '', text)
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)
    text = re.sub(r'\w*\d\w*', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [17]:
df['Message'].apply(wordopt)

0       go until jurong point crazy available only in ...
1                                 ok lar joking wif u oni
2       free entry in a wkly comp to win fa cup final ...
3             u dun say so early hor u c already then say
4       nah i dont think he goes to usf he lives aroun...
                              ...
5567    this is the time we have tried contact u u hav...
5568                  will ü b going to esplanade fr home
5569    pity was in mood for that soany other suggestions
5570    the guy did some bitching but i acted like id ...
5571                            rofl its true to its name
Name: Message, Length: 5572, dtype: object

In [18]:
df.loc[:, 'cleaned'] = df['Message'].apply(wordopt)

In [19]:
x=df['cleaned']
y=df['Category']

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.02)

In [21]:
x_test

2813    say this slowly godi love you amp i need youcl...
3858    no but we found a diff farm shop to buy some c...
2249                          will you like to be spoiled
5166    y she dun believe leh i tot i told her its tru...
3380                          dear umma she called me now
                              ...
279         just sent it so what type of food do you like
951              awesome lemme know whenever youre around
5262                                did you see that film
1042                         im in class will holla later
2762    i am not sure about night menu i know only abo...
Name: cleaned, Length: 112, dtype: object

In [22]:
y_test

2813    0.0
3858    0.0
2249    0.0
5166    0.0
3380    0.0
       ...
279     0.0
951     0.0
5262    0.0
1042    0.0
2762    0.0
Name: Category, Length: 112, dtype: float64

In [23]:
y_train

899     0.0
2598    0.0
4023    0.0
607     1.0
3321    0.0
       ...
1216    0.0
1162    0.0
3120    0.0
2485    0.0
4095    0.0
Name: Category, Length: 5460, dtype: float64

In [24]:
from sklearn.feature_extraction.text import CountVectorizer
count=CountVectorizer()
x_train_vec=count.fit_transform(x_train).toarray()
x_test_vec=count.transform(x_test).toarray()

In [25]:
x_test_vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(112, 8140))

In [26]:
x_train_vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(5460, 8140))

In [27]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [28]:
model.fit(x_train_vec,y_train)

LogisticRegression()

In [29]:
model.score(x_train_vec,y_train)

0.9956043956043956

In [30]:
y_pred=classifier.predict(x_test_vec)
y_pred

NameError: name 'classifier' is not defined

In [ ]:
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm=confusion_matrix(y_test,y_pred)

disp = ConfusionMatrixDisplay(cm, display_labels=["ham", "spam"])
disp.plot()

plt.title("Confusion Matrix - logistic regression")
plt.show()

In [ ]:
model

In [31]:
from sklearn.pipeline import Pipeline 
from sklearn.ensemble import RandomForestClassifier

In [32]:
from sklearn.pipeline import Pipeline

In [33]:
Pipline_model=Pipeline([('vectorizer',CountVectorizer(preprocessor=wordopt)),('classifier',RandomForestClassifier(n_estimators=9,class_weight='balanced'))])

In [34]:
Pipline_model.fit(x_train,y_train)

Pipeline(steps=[('vectorizer',
                 CountVectorizer(preprocessor=<function wordopt at 0x00000213D80B7560>)),
                ('classifier',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=9))])

In [35]:
Pipline_model.predict(['you won a grand price of 10 lakhs'])

array([0.])

In [36]:
def see(txt):
    if txt.strip()=='':
        return 'enter something'
    val=Pipline_model.predict([txt])
    if txt==0:
        return 'ham'
    else:
        return 'spam'

In [37]:
see('you won a grand price of 10 lakhs')

'spam'

In [38]:
import joblib

In [40]:
joblib.dump(Pipline_model,'spam_mail.pkl')

['spam_mail.pkl']